# Generated by Django 4.2.1 on 2023-05-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="chambre",
            fields=[
                (
                    "id_c",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_chmb", models.CharField(max_length=300)),
                ("prix_chmb", models.DecimalField(decimal_places=2, max_digits=8)),
                ("disponible", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="personne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("Tel", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_plat", models.IntegerField()),
                ("nom_plat", models.CharField(max_length=200)),
                ("prix_plat", models.DecimalField(decimal_places=2, max_digits=8)),
                ("disponibilite_plat", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="reserver_chambre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reservation", models.DateField()),
                (
                    "id_c",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="dall_diamm.chambre",
                    ),
                ),
                (
                    "id_p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="dall_diamm.personne",
                    ),
                ),
            ],
            options={
                "db_table": "dall_diamm_reserver_chambre",
            },
        ),
    ]
