# Generated by Django 4.2.1 on 2023-05-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="voiture",
            fields=[
                ("num_voit", models.IntegerField(primary_key=True, serialize=False)),
                ("nom_voit", models.CharField(max_length=200)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
