# Generated by Django 4.2.1 on 2023-05-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="chambre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_chmb", models.CharField(max_length=300)),
                ("prix_chmb", models.DecimalField(decimal_places=2, max_digits=8)),
                ("disponible", models.BooleanField()),
            ],
        ),
    ]
