# Generated by Django 4.2.1 on 2023-06-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="voiture",
            fields=[
                ("idV", models.AutoField(primary_key=True, serialize=False)),
                ("marque", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("types", models.CharField(max_length=200)),
                ("capacite", models.IntegerField()),
                ("transmission", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=2000)),
                ("annee", models.IntegerField()),
                ("couleur", models.CharField(max_length=200)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
