# Generated by Django 4.2.1 on 2023-05-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="voiture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_voit", models.CharField(max_length=200)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date_livraison", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="etudiant",
        ),
    ]
