# Generated by Django 4.2.1 on 2023-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0002_voiture_delete_etudiant"),
    ]

    operations = [
        migrations.CreateModel(
            name="chambre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_chmb", models.IntegerField()),
                ("nom_chmb", models.CharField(max_length=300)),
                ("prix_chmb", models.IntegerField()),
                ("date_location", models.DateField()),
                ("disponible", models.BooleanField()),
            ],
        ),
    ]
