# Generated by Django 4.2.1 on 2023-06-13 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0002_voiture"),
    ]

    operations = [
        migrations.AddField(
            model_name="personne",
            name="mot_de_passe",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.CreateModel(
            name="reservationVoitures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=30)),
                ("nom", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=100)),
                ("telephone", models.CharField(max_length=10)),
                ("service", models.CharField(max_length=30)),
                ("date_loc", models.DateTimeField()),
                ("permis", models.FileField(upload_to="permis/")),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dall_diamm.voiture",
                    ),
                ),
            ],
        ),
    ]
