# Generated by Django 4.2.1 on 2023-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0003_chambre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chambre",
            name="prix_chmb",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
