# Generated by Django 4.2.1 on 2023-05-22 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0003_personne"),
    ]

    operations = [
        migrations.CreateModel(
            name="reserver_chambre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reservation", models.DateField()),
                (
                    "id_c",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dall_diamm.chambre",
                    ),
                ),
                (
                    "id_p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dall_diamm.personne",
                    ),
                ),
            ],
        ),
    ]
