# Generated by Django 4.2.1 on 2023-05-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0003_personne"),
    ]

    operations = [
        migrations.CreateModel(
            name="restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_plat", models.IntegerField()),
                ("nom_plat", models.CharField(max_length=200)),
                ("prix_plat", models.DecimalField(decimal_places=2, max_digits=8)),
                ("img", models.ImageField(upload_to="")),
                ("disponibilite_plat", models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name="chambre",
            old_name="id_c",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="personne",
            old_name="id_p",
            new_name="id",
        ),
    ]
