# Generated by Django 4.2.1 on 2023-06-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0003_personne_mot_de_passe_reservationvoitures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personne",
            name="nom",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
