# Generated by Django 4.2.1 on 2023-05-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0004_restaurant_rename_id_c_chambre_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chambre",
            old_name="id",
            new_name="id_c",
        ),
    ]
