# Generated by Django 4.2.1 on 2023-06-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0004_alter_personne_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personne",
            name="email",
            field=models.EmailField(default="", max_length=254, null=True),
        ),
    ]
