# Generated by Django 4.2.1 on 2023-06-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dall_diamm", "0005_alter_personne_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personne",
            name="mot_de_passe",
            field=models.CharField(default="", max_length=20, null=True),
        ),
    ]
