# Generated by Django 4.2.1 on 2023-06-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dall_diamm",
            "0012_alter_personne_email_alter_personne_mot_de_passe_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="disponibilite_plat",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="id",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="num_plat",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="id_plat",
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="img_plat",
            field=models.ImageField(default=None, upload_to=""),
            preserve_default=False,
        ),
    ]
